---
jobs:
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-web-app
  - put: resource-deploy-web-app
    params:
      manifest: resource-web-app/manifest.yml

resources:
- name: resource-web-app
  type: git
  source:
    uri: https://github.com/tle264/testConcourse.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: EMAIL
    password: PASSWORD
    organization: ORG
    space: SPACE
    skip_cert_check: false